language: python
python:
  # - 2.7
  # - 3.5
  - 3.6
before_install:
  - python --version
  # - pip install -U pip
  # - pip install -U pytest
  # - pip install codecov
install:
  # works
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

  # - pip install ".[test]" . # install package + test dependencies
  - pip list
script: 
  - pytest