
##############################################
# ref. https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
##############################################

language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  # - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

  #let's see what was installed
  # - pip list
script: 
  - pytest --cov=lazy_regression_tests --cov-config=.coveragerc

after_success:
  - codecov